

//NGƯỜI DÙNG
export const LAY_DANH_SACH_NGUOI_DUNG_ACTION = 'LAY_DANH_SACH_NGUOI_DUNG_ACTION';
export const THEM_NGUOI_DUNG_MOI_ACTION = 'THEM_NGUOI_DUNG_MOI_ACTION';
export const XOA_NGUOI_DUNG_ACTION = 'XOA_NGUOI_DUNG_ACTION';
export const TAI_KHOAN_NGUOI_DUNG_ACTION = 'TAI_KHOAN_NGUOI_DUNG_ACTION';
export const CHINH_SUA_NGUOI_DUNG_ACTION = 'CHINH_SUA_NGUOI_DUNG_ACTION';
export const LAY_THONG_TIN_TAI_KHOAN = 'LAY_THONG_TIN_TAI_KHOAN';
export const CHANGE_HE_THONG_RAP_ACTION = 'CHANGE_HE_THONG_RAP_ACTION';

//ĐĂNG NHẬP
export const DANG_NHAP_ACTION = 'DANG_NHAP_ACTION';