//PHIM
export const LAY_DANH_SACH_PHIM_ACTION = 'LAY_DANH_SACH_PHIM_ACTION';
export const THEM_PHIM_MOI_ACTION = 'THEM_PHIM_MOI_ACTION';
export const XOA_PHIM_ACTION = 'XOA_PHIM_ACTION';
export const MA_PHIM_CHINH_SUA_ACTION = 'MA_PHIM_CHINH_SUA_ACTION';
export const LAY_HE_THONG_RAP_ACTION = 'LAY_HE_THONG_RAP_ACTION';
export const LAY_HE_THONG_CUM_RAP_ACTION = 'LAY_HE_THONG_CUM_RAP_ACTION';
export const THONG_TIN_LICH_CHIEU_ACTION = 'THONG_TIN_LICH_CHIEU_ACTION';
export const CHANGE_HE_THONG_RAP_ACTION = 'CHANGE_HE_THONG_RAP_ACTION';